const fetch = require("node-fetch");

function main() {
  fetch("https://l374cc62kc.execute-api.us-east-2.amazonaws.com/Prod/camps")
    .then((res) => res.json())
    .then((data) => {
      console.log(data);
    })
    .catch(console.log);
}

const campData = [
  {
    year: 2019,
    name: "3907",
    identifies: "Ally Camp",
    url: "",
    facebook: "https://www.facebook.com/camp3907",
    location: { frontage: "4:30", intersection: "B", string: "4:30 & B" },
  },
  {
    year: 2019,
    name: "3SP (Third Space Place)",
    identifies: "Ally Camp",
    url: "",
    facebook: "https://www.facebook.com/groups/3SPThirdSpacePlace/",
    location: { frontage: "G", intersection: "4:15", string: "G & 4:15" },
  },
  {
    year: 2019,
    name: "Astro Cats",
    identifies: "Ally Camp",
    url: "",
    facebook: "https://www.facebook.com/groups/Astrocats.2014/",
    location: { frontage: "C", intersection: "7:15", string: "C & 7:15" },
  },
  {
    year: 2019,
    name: "Astropups",
    identifies: "LGBTQ",
    url: "",
    facebook: "https://facebook.com/groups/astropupspublic/",
    location: { frontage: "D", intersection: "4:15", string: "D & 4:15" },
  },
  {
    year: 2019,
    name: "BAAAHS",
    identifies: "LGBTQ",
    url: "",
    facebook: "https://www.facebook.com/groups/baaahs/",
    location: { frontage: "4:30", intersection: "D", string: "4:30 & D" },
  },
  {
    year: 2019,
    name: "Bad Asstronauts",
    identifies: "LGBTQ",
    url: "",
    facebook: "https://facebook.com/badasstronauts/",
    location: { frontage: "7:30", intersection: "E", string: "7:30 & E" },
  },
  {
    year: 2019,
    name: "Bat Haus",
    identifies: "LGBTQ",
    url: "",
    facebook: "https://facebook.com/thebatcarnival",
    location: { frontage: "H", intersection: "6:45", string: "H & 6:45" },
  },
  {
    year: 2019,
    name: "BeardHaus",
    identifies: "Gay / Male Identified",
    url: "",
    facebook: "https://www.facebook.com/beardhausSF/",
    location: { frontage: "D", intersection: "4:15", string: "D & 4:15" },
  },
  {
    year: 2019,
    name: "Big GIrtha",
    identifies: "LGBTQ",
    url: "",
    facebook: "https://www.facebook.com/BigGirtha/",
    location: { frontage: "E", intersection: "4:15", string: "E & 4:15" },
  },
  {
    year: 2019,
    name: "Black Rock Gladiators",
    identifies: "LGBTQ",
    url: "",
    facebook: "https://facebook.com/blackrockgladiators",
    location: {
      frontage: "Esplanade",
      intersection: "3:00",
      string: "Esplanade & 3:00",
    },
  },
  {
    year: 2019,
    name: "Black Rock Roller Disco",
    identifies: "Ally Camp",
    url: "",
    facebook: "https://www.facebook.com/Black-Rock-Roller-Disco-178359878930/",
    location: {
      frontage: "Esplanade",
      intersection: "7:15",
      string: "Esplanade & 7:15",
    },
  },
  {
    year: 2019,
    name: "Bubble Lounge ",
    identifies: "LGBTQ",
    url: "https://www.bubbleloungers.com/",
    facebook: "",
    location: { frontage: "A", intersection: "5:45", string: "A & 5:45" },
  },
  {
    year: 2019,
    name: "BuddhaCamp @ the Lotus Dome",
    identifies: "Ally Camp",
    url: "Http://www.buddhacamp.org",
    facebook: "",
    location: { frontage: "5:00", intersection: "E", string: "5:00 & E" },
  },
  {
    year: 2019,
    name: "Burner Buddies",
    identifies: "LGBTQ",
    url: "",
    facebook: "https://www.facebook.com/groups/burnerbuddies/",
    location: { frontage: "4:30", intersection: "J", string: "4:30 & J" },
  },
  {
    year: 2019,
    name: "Camp Be Bothered",
    identifies: "LGBTQ",
    url: "",
    facebook: "https://www.facebook.com/campbebothered",
    location: { frontage: "D", intersection: "4:15", string: "D & 4:15" },
  },
  {
    year: 2019,
    name: "Camp Beaverton",
    identifies: "Lesbian / Female Identified",
    url: "http://www.campbeaverton.org",
    facebook: "",
    location: { frontage: "C", intersection: "7:45", string: "C & 7:45" },
  },
  {
    year: 2019,
    name: "Camp Cabaret & Deli",
    identifies: "LGBTQ",
    url: "",
    facebook: "https://www.facebook.com/groups/266301744040579/",
    location: { frontage: "E", intersection: "7:15", string: "E & 7:15" },
  },
  {
    year: 2019,
    name: "Camp Connect Mour",
    identifies: "Ally Camp",
    url: "",
    facebook: "",
    location: { frontage: "C", intersection: "8:15", string: "C & 8:15" },
  },
  {
    year: 2019,
    name: "Camp Gender Blenders",
    identifies: "Trans / GNC / Non-binary",
    url: "https://genderblenders.org",
    facebook: "",
    location: { frontage: "D", intersection: "7:45", string: "D & 7:45" },
  },
  {
    year: 2019,
    name: "Celestial Bodies",
    identifies: "LGBTQ",
    url: "https://campcelestialbodies.org",
    facebook: "",
    location: { frontage: "7:30", intersection: "G", string: "7:30 & G" },
  },
  {
    year: 2019,
    name: "Champagne Lounge",
    identifies: "Ally Camp",
    url: "",
    facebook: "https://facebook.com/champagnelounge",
    location: {
      frontage: "Rod's Road",
      intersection: "5:30",
      string: "Rod's Road @ 5:30",
    },
  },
  {
    year: 2019,
    name: "CHURCH OF NOW",
    identifies: "LGBTQ",
    url: "",
    facebook: "https://www.facebook.com/ChurchOfNowBM",
    location: { frontage: "4:00", intersection: "C", string: "4:00 & C" },
  },
  {
    year: 2019,
    name: "Comfort & Joy",
    identifies: "LGBTQ",
    url: "http://playajoy.org",
    facebook: "",
    location: { frontage: "7:00", intersection: "D", string: "7:00 & D" },
  },
  {
    year: 2019,
    name: "Comfy Cozy Voodoo Lounge",
    identifies: "Ally Camp",
    url: "http://www.comfycozyvoodoolounge.com",
    facebook: "",
    location: { frontage: "7:30", intersection: "A", string: "7:30 & A" },
  },
  {
    year: 2019,
    name: "Conception",
    identifies: "LGBTQ",
    url: "http://www.CampConception.com",
    facebook: "",
    location: { frontage: "G", intersection: "4:15", string: "G & 4:15" },
  },
  {
    year: 2019,
    name: "Cornstars",
    identifies: "Ally Camp",
    url: "",
    facebook: "",
    location: { frontage: "9:30", intersection: "D", string: "9:30 & D" },
  },
  {
    year: 2019,
    name: "Dante’s InFURno",
    identifies: "LGBTQ",
    url: "https://dantesinfurno.com/",
    facebook: "",
    location: { frontage: "7:30", intersection: "B", string: "7:30 & B" },
  },
  {
    year: 2019,
    name: "Date to be Rare",
    identifies: "Ally Camp",
    url: "http://www.daretoberare.rocks/",
    facebook: "",
    location: { frontage: "D", intersection: "2:15", string: "D & 2:15" },
  },
  {
    year: 2019,
    name: "Dickstracted Camp",
    identifies: "Gay / Male Identified",
    url: "",
    facebook: "",
    location: { frontage: "7:30", intersection: "E", string: "7:30 & E" },
  },
  {
    year: 2019,
    name: "Dilated Peoples",
    identifies: "LGBTQ",
    url: "",
    facebook: "",
    location: { frontage: "D", intersection: "4:15", string: "D & 4:15" },
  },
  {
    year: 2019,
    name: "Down Low Club",
    identifies: "Gay / Male Identified",
    url: "",
    facebook: "https://facebook.com/groups/557666564336453",
    location: { frontage: "F", intersection: "7:15", string: "F & 7:15" },
  },
  {
    year: 2019,
    name: "dust & stars ",
    identifies: "LGBTQ",
    url: "",
    facebook: "https://facebook.com/dust&stars2019",
    location: { frontage: "G", intersection: "7:15", string: "G & 7:15" },
  },
  {
    year: 2019,
    name: "Dusty Mule Saloon & Playground",
    identifies: "Ally Camp",
    url: "",
    facebook: "https://www.facebook.com/groups/135911910547964/",
    location: { frontage: "H", intersection: "4:15", string: "H & 4:15" },
  },
  {
    year: 2019,
    name: "Elvis Wedding Chapel",
    identifies: "LGBTQ",
    url: "",
    facebook: "",
    location: { frontage: "7:30", intersection: "G", string: "7:30 & G" },
  },
  {
    year: 2019,
    name: "Entheos",
    identifies: "Ally Camp",
    url: "http://www.entheosrising.org",
    facebook: "",
    location: { frontage: "4:00", intersection: "F", string: "4:00 & F" },
  },
  {
    year: 2019,
    name: "Fancy Flamingo Society",
    identifies: "Ally Camp",
    url: "",
    facebook: "",
    location: { frontage: "6:00", intersection: "K", string: "6:00 & K" },
  },
  {
    year: 2019,
    name: "Flaming Flamingos 54. (Illumination Village)",
    identifies: "LGBTQ",
    url: "",
    facebook: "",
    location: {
      frontage: "Esplanade",
      intersection: "3:15",
      string: "Esplanade & 3:15",
    },
  },
  {
    year: 2019,
    name: "FUR",
    identifies: "LGBTQ",
    url: "http://furryburners.com",
    facebook: "",
    location: { frontage: "7:30", intersection: "E", string: "7:30 & E" },
  },
  {
    year: 2019,
    name: "Gay Turtles",
    identifies: "Gay / Male Identified",
    url: "",
    facebook: "",
    location: { frontage: "E", intersection: "4:15", string: "E & 4:15" },
  },
  {
    year: 2019,
    name: "Gaylactic Invaders Village",
    identifies: "LGBTQ",
    url: "",
    facebook: "",
    location: { frontage: "7:00", intersection: "C", string: "7:00 & C" },
  },
  {
    year: 2019,
    name: "GlamCocks",
    identifies: "LGBTQ",
    url: "https://www.glamcocks.com/",
    facebook: "",
    location: { frontage: "7:00", intersection: "B", string: "7:00 & B" },
  },
  {
    year: 2019,
    name: "Gymnasium",
    identifies: "Ally Camp",
    url: "http://www.gymnasiumburningman.com",
    facebook: "",
    location: { frontage: "7:30", intersection: "G", string: "7:30 & G" },
  },
  {
    year: 2019,
    name: "Heavy Petting Zoo",
    identifies: "Ally Camp",
    url: "",
    facebook: "https://www.facebook.com/heavypettingzooartcar/",
    location: { frontage: "I", intersection: "7:15", string: "I & 7:15" },
  },
  {
    year: 2019,
    name: "In Dust We Trust ",
    identifies: "LGBTQ",
    url: "",
    facebook: "",
    location: { frontage: "4:00", intersection: "I", string: "4:00 & I" },
  },
  {
    year: 2019,
    name: "Land of Monkey",
    identifies: "LGBTQ",
    url: "",
    facebook: "https://www.facebook.com/thelandofmonkey/",
    location: { frontage: "C", intersection: "7:45", string: "C & 7:45" },
  },
  {
    year: 2019,
    name: "Lil Crackwhores",
    identifies: "LGBTQ",
    url: "",
    facebook: "",
    location: { frontage: "D", intersection: "6:45", string: "D & 6:45" },
  },
  {
    year: 2019,
    name: "Lustre Village",
    identifies: "LGBTQ",
    url: "",
    facebook: "",
    location: { frontage: "4:00", intersection: "D", string: "4:00 & D" },
  },
  {
    year: 2019,
    name: "Magic potion ",
    identifies: "Ally Camp",
    url: "",
    facebook: "",
    location: { frontage: "G", intersection: "6:45", string: "G & 6:45" },
  },
  {
    year: 2019,
    name: "My Reply Is Yes",
    identifies: "Ally Camp",
    url: "",
    facebook: "https://www.facebook.com/myreplyisyes/",
    location: { frontage: "H", intersection: "8:15", string: "H & 8:15" },
  },
  {
    year: 2019,
    name: "Mystopia",
    identifies: "LGBTQ",
    url: "https://mystopia.camp",
    facebook: "",
    location: { frontage: "7:30", intersection: "E", string: "7:30 & E" },
  },
  {
    year: 2019,
    name: "Paradise Motel",
    identifies: "LGBTQ",
    url: "https://www.paradisemotel.camp/",
    facebook: "",
    location: { frontage: "8:00", intersection: "D", string: "8:00 & D" },
  },
  {
    year: 2019,
    name: "Patsy's Hangout",
    identifies: "LGBTQ",
    url: "https://www.patsyshangout.org",
    facebook: "",
    location: { frontage: "B", intersection: "7:15", string: "B & 7:15" },
  },
  {
    year: 2019,
    name: "Picklebackers",
    identifies: "LGBTQ",
    url: "",
    facebook: "",
    location: { frontage: "G", intersection: "2:45", string: "G & 2:45" },
  },
  {
    year: 2019,
    name: "Pigmalions",
    identifies: "LGBTQ",
    url: "",
    facebook: "",
    location: { frontage: "D", intersection: "7:45", string: "D & 7:45" },
  },
  {
    year: 2019,
    name: "Pink Fuzzy Monkey",
    identifies: "LGBTQ",
    url: "",
    facebook: "",
    location: { frontage: "C", intersection: "6:45", string: "C & 6:45" },
  },
  {
    year: 2019,
    name: "Pyramid Scheme",
    identifies: "LGBTQ",
    url: "",
    facebook: "",
    location: { frontage: "4:30", intersection: "E", string: "4:30 & E" },
  },
  {
    year: 2019,
    name: "Religious As Fuck",
    identifies: "Ally Camp",
    url: "https://religiousafcamp.com",
    facebook: "",
    location: { frontage: "C", intersection: "3:45", string: "C & 3:45" },
  },
  {
    year: 2019,
    name: "Remote Control",
    identifies: "Gay / Male Identified",
    url: "http://www.campremotecontrol.com",
    facebook: "",
    location: { frontage: "I", intersection: "7:45", string: "I & 7:45" },
  },
  {
    year: 2019,
    name: "Secred Hare",
    identifies: "LGBTQ",
    url: "",
    facebook: "",
    location: { frontage: "G", intersection: "7:15", string: "G & 7:15" },
  },
  {
    year: 2019,
    name: "Space Racers",
    identifies: "LGBTQ",
    url: "",
    facebook: "",
    location: { frontage: "G", intersection: "7:45", string: "G & 7:45" },
  },
  {
    year: 2019,
    name: "tHAIRapy Salo(o)n",
    identifies: "LGBTQ",
    url: "",
    facebook: "",
    location: { frontage: "C", intersection: "6:45", string: "C & 6:45" },
  },
  {
    year: 2019,
    name: "Tickled Mink",
    identifies: "LGBTQ",
    url: "",
    facebook: "https://www.facebook.com/tickledminkBRC/",
    location: { frontage: "D", intersection: "7:45", string: "D & 7:45" },
  },
  {
    year: 2019,
    name: "Tropical Treehouse",
    identifies: "LGBTQ",
    url: "",
    facebook: "",
    location: { frontage: "D", intersection: "7:35", string: "D & 7:35" },
  },
  {
    year: 2019,
    name: "Yes Please",
    identifies: "LGBTQ",
    url: "",
    facebook: "https://www.facebook.com/groups/120420311355626/",
    location: { frontage: "C", intersection: "6:45", string: "C & 6:45" },
  },
];

function addOneCamp(camp) {
  fetch("https://l374cc62kc.execute-api.us-east-2.amazonaws.com/Prod/camps", {
    method: "post",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(camp),
  })
    .then((res) => res.json())
    .then((data) => {
      console.log(data);
    })
    .catch(console.log);
}

campData.map((o) => {
  addOneCamp(o);
});
