// TODO  moved this all into shared

export const campIdentifications = [
  "LGBTQ",
  "Lesbian / Female Identified",
  "Gay / Male Identified",
  "Trans / GNC / Non-binary",
  "Ally Camp",
];

export const defaultYear = new Date().getFullYear();

// TODO delete testData
export const testData = [
  {
    updated: "2020-05-21T23:14:25.597Z",
    identifies: "Trans / GNC / Non-binary",
    created: "2020-05-21T21:26:46.726Z",
    year: 2019,
    placed: "yes",
    name: "Camp Gender Blenders",
    url: "https://genderblenders.org",
    facebook: "https://www.facebook.com/groups/genderblender/",
    email: "info@genderblenders.org",
    location: {
      string: "D & 7:45",
      frontage: "D",
      intersection: "7:45",
      intersection_type: "&",
    },
    about:
      "Gender Blender is a community committed to creating safe, awesome, fun, creative spaces for trans, gender queer, gender variant, gender nonconforming, queens, kings, and those of us that are shape shifting the gender binary.",
    image: "GenderBlenders.jpg",
  },
  {
    updated: "2020-05-21T23:13:10.176Z",
    since: 2001,
    identifies: "LGBTQ",
    created: "2020-05-21T00:19:24.076Z",
    year: 2019,
    placed: "yes",
    name: "Astropups",
    facebook: "https://facebook.com/groups/astropupspublic/",
    location: {
      string: "D & 4:15",
      frontage: "D",
      intersection: "4:15",
      intersection_type: "&",
    },
    about:
      "Since 2001, the Astropups have been known for providing a cool (and furry) oasis on the playa where countless queer (and queer-friendly) Burners have crossed paths and met new friends.",
    image: "Astropups.jpg",
  },
  {
    updated: "2020-05-21T23:13:10.176Z",
    identifies: "LGBTQ",
    created: "2020-05-21T00:19:24.076Z",
    year: 2019,
    placed: "yes",
    name: "BAAAHS",
    url: "http://www.baaahs.org/",
    email: "info@baaahs.org",
    facebook: "https://www.facebook.com/groups/baaahs/",
    location: {
      string: "4:30 & D",
      frontage: "4:30",
      intersection: "D",
      intersection_type: "&",
    },
    about: "Big-ass amazingly awesome homosexual sheep",
    image: "BAAAHS.jpg",
    join: {
      open: true,
      message:
        "We are always excited to welcome new BAAAHS campers. If you are interested in joining BAAAHS, attend some of our events, listed on the Facebook page.",
    },
  },
  {
    updated: "2020-05-21T23:13:10.176Z",
    identifies: "LGBTQ",
    created: "2020-05-21T00:19:24.076Z",
    year: 2019,
    placed: "yes",
    name: "Bad Asstronauts",
    facebook: "https://www.facebook.com/badasstronauts/",
    location: {
      string: "7:30 & E",
      frontage: "7:30",
      intersection: "E",
      intersection_type: "&",
    },
    about:
      "We are the Bad Asstronauts, a group of Denver-based friends who also travel to Burning Man, Apo & beyond.",
    image: "BadAsstronauts.jpg",
  },
  {
    updated: "2020-05-21T23:13:10.176Z",
    identifies: "Gay / Male Identified",
    created: "2020-05-21T00:19:24.076Z",
    year: 2019,
    placed: "yes",
    name: "Future Turtles",
    url: "https://futureturtles.com/",
    email: "joel@spolsky.com",
    facebook: "https://facebook.com/futureturtle",
    instagram: "https://www.instagram.com/futureturtles/",
    location: {
      string: "E & 4:15",
      frontage: "E",
      intersection: "4:15",
      intersection_type: "&",
    },
    about:
      "The Future Turtles are a disorganized bunch of friends camping together at Burning Man since 2018 without any drama, death, or injury.",
    image: "FutureTurtles.jpg",
  },
  {
    updated: "2020-05-21T23:13:10.176Z",
    identifies: "LGBTQ",
    created: "2020-05-21T00:19:24.076Z",
    year: 2019,
    placed: "yes",
    name: "Paradise Motel",
    url: "https://www.paradisemotel.camp/",
    email: " contact@paradisemotel.camp",
    facebook: "https://www.facebook.com/groups/paradisemotel",
    location: {
      string: "8:00 & D",
      frontage: "8:00",
      intersection: "D",
      intersection_type: "&",
    },
    about:
      'We\'re a flamboyance of fun-loving goofballs from mainly the Bay Area (and all across the gender and sexuality spectra) who invite weary travelers to stop in for a snow cone and enjoy featured music and activities every day while lounging in the shade by our "pool".',
    image: "ParadiseMotel.jpg",
  },
];

export const streets = [
  "Esplanade",
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "2:00",
  "2:15",
  "2:30",
  "2:45",
  "3:00",
  "3:15",
  "3:30",
  "3:45",
  "4:00",
  "4:15",
  "4:30",
  "4:45",
  "5:00",
  "5:15",
  "5:30",
  "5:45",
  "6:00",
  "6:15",
  "6:30",
  "6:45",
  "7:00",
  "7:15",
  "7:30",
  "7:45",
  "8:00",
  "8:15",
  "8:30",
  "8:45",
  "9:00",
  "9:15",
  "9:30",
  "9:45",
  "10:00",
  "Rod's Road",
  "Center Camp Plaza",
];
